"""
Django settings for Shop project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.urls import reverse_lazy
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d988i@hopz6ts)(=)fw$l3j#)7ky%^$&y4wer#lh$%+zv$bslh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djmoney',
    'appSettings',
    'appShop'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


UNFOLD = {
    "SITE_HEADER": "Магазин",
    "SITE_SUBHEADER": "Администрирование",
    "SITE_DROPDOWN": [
         {
             "icon": "Shopping_Bag_Speed",
             "title": "Ozon",
             "link": "https://www.ozon.ru",
         },
    ],
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Пользователи и группы",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Доступы",
                        "icon": "Ad_Group",
                        # Прилижение_модель_changelist
                        "link": reverse_lazy("admin:auth_group_changelist")
                    },
                    {
                        "title": "Все пользователи",
                        "icon": "Account_Circle",
                        # Прилижение_модель_changelist
                        "link": reverse_lazy("admin:auth_user_changelist")
                    }
                ]
            },
            {
                "title": "Управление магазином",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Продукты",
                        "icon": "Shopping_Basket",
                        "link": reverse_lazy("admin:appShop_product_changelist")
                    },
                    {
                        "title": "Категории",
                        "icon": "List",
                        "link": reverse_lazy("admin:appShop_category_changelist")
                    },
                ]

            }
        ]
    },
    "COLORS": {
        "primary": {
            "50": "240, 253, 244",
            "100": "220, 252, 231",
            "200": "187, 247, 208",
            "300": "134, 239, 172",
            "400": "74, 222, 128",
            "500": "34, 197, 94",
            "600": "22, 163, 74",
            "700": "21, 128, 61",
            "800": "22, 101, 52",
            "900": "20, 83, 45",
            "950": "5, 46, 22"
        },
    },
}

CURRENCIES = ('RUB', 'USD', 'EUR')
CURRENCY_CHOICES = [('RUB', 'Рублей ₽'), ('USD', 'Доллары $'), ('EUR', 'Евры €')]