# Generated by Django 5.2.5 on 2025-08-20 16:55

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Доллары $'), ('EUR', 'Евры €'), ('RUB', 'Рублей ₽')], default=None, editable=False, max_length=3),
        ),
    ]
